module.exports = {
  postTotalInformations: /<article\s*role="presentation"\s*class="standard-post"\s*data-index="\d+"(?:[^@](?!href))+.href="[^"]+"\s*>(?:<img\s*src="[^"]+")*\s*(?:[^@](?!post-attribution__timeago))+.post-attribution__timeago"\s*href="[^"]+"\s*><time\s*datetime="(?:(?:[^,]+),\s*[\d:]+\s*(?:PM|AM))"(?:[^@](?!post-attribution__category))+.post-attribution__category"\s*href="[^"]+"\s*>dans\s*[^<]+(?:.(?!post-info__title-link))+.post-info__title-link"\s*href="[^"]+"\s*>[^<]+<\/a\s*>\s*<\/header>(?:[^@](?!(?:entity-content)|(?:post-poll)))+.(?:(?:(?:entity-content)|(?:post-poll"\s*itemscope=""\s*itemType="http:\/\/schema.org\/Question))">\s*(?:(?:(?:<p>(?:.(?!p>))+<\/p>)|(?:<ul>(?:.(?!ul>))+<\/ul>)|(?:(?:<div\s*class="post-poll__answer"\s*role="presentation"\s*itemscope=""\s*itemType="http:\/\/schema.org\/Answer"><span\s*class="post-poll__text"\s*itemProp="text">[^<]+<\/span><span\s*class="post-poll__votes"\s*itemProp="upvoteCount"><\/span><\/div>)+<div\s*class="post-poll__vote"><button\s*class="wds-button\s*post-poll__vote-btn\s*is-themed"\s*disabled="">Voter<\/button><p\s*class="post-poll__total-votes"\s*itemProp="answerCount"\s*role="presentation">[^<]+<\/p><\/div><\/div>)|(?:<div\s*class="post__image-wrapper">\s*<img\s*class="post__image"\s*src="[^"]+"\s*alt="Fandom\s*Image"\s*itemprop="image"\s*role="presentation"\s*\/>\s*<\/div>\s*)|(?:<p><br\s*\/><\/p>)|(?:<div (?:.(?!\/div))+\s*<\/div>))+))\s*(?:[^\\](?!itemProp="upvoteCount))+.itemProp="upvoteCount">\d+(?:[^@](?!itemProp="commentCount))+.itemProp="commentCount">\d+/gis,

  getInformationsPost: /<article\s*role="presentation"\s*class="standard-post"\s*data-index="\d+"(?:[^@](?!href))+.href="([^"]+)"\s*>(?:<img\s*src="([^"]+)")*\s*(?:[^@](?!post-attribution__timeago))+.post-attribution__timeago"\s*href="([^"]+)"\s*><time\s*datetime="((?:[^,]+),\s*([\d:]+)\s*(?:PM|AM))"(?:[^@](?!post-attribution__category))+.post-attribution__category"\s*href="([^"]+)"\s*>dans\s*([^<]+)(?:.(?!post-info__title-link))+.post-info__title-link"\s*href="([^"]+)"\s*>([^<]+)<\/a\s*>\s*<\/header>(?:[^@](?!(?:entity-content)|(?:post-poll)))+.(?:(?:(?:entity-content)|(?:post-poll"\s*itemscope=""\s*itemType="http:\/\/schema.org\/Question))">\s*((?:(?:<p>(?:.(?!p>))+<\/p>)|(?:<ul>(?:.(?!ul>))+<\/ul>)|(?:(?:<div\s*class="post-poll__answer"\s*role="presentation"\s*itemscope=""\s*itemType="http:\/\/schema.org\/Answer"><span\s*class="post-poll__text"\s*itemProp="text">[^<]+<\/span><span\s*class="post-poll__votes"\s*itemProp="upvoteCount"><\/span><\/div>)+<div\s*class="post-poll__vote"><button\s*class="wds-button\s*post-poll__vote-btn\s*is-themed"\s*disabled="">Voter<\/button><p\s*class="post-poll__total-votes"\s*itemProp="answerCount"\s*role="presentation">([^<]+)<\/p><\/div><\/div>)|(?:<div\s*class="post__image-wrapper">\s*<img\s*class="post__image"\s*src="[^"]+"\s*alt="Fandom\s*Image"\s*itemprop="image"\s*role="presentation"\s*\/>\s*<\/div>\s*)|(?:<p><br\s*\/><\/p>)|(?:<div (?:.(?!\/div))+\s*<\/div>))+))\s*(?:[^\\](?!itemProp="upvoteCount))+.itemProp="upvoteCount">(\d+)(?:[^@](?!itemProp="commentCount))+.itemProp="commentCount">(\d+)/is,

  regBlogs: /<div class="blog-listing__post">\s*<div class="blog-listing__post-details">\s*<div>\s*<a\s*class="blog-listing__user-avatar"\s*href="\/fr\/wiki\/Utilisateur:[^"]+"\s*>\s*<img\s*class="blog-listing__user-avatar__image"\s*src="(?:[^"]+)"\s*alt="[^"]+"\s*\/>\s*<\/a>\s*<a\s*href="[^"]+"\s*class="blog-listing__user-name"\s*>(?:[^<]+)<\/a\s*>\s*<span class="blog-listing__bullet">\s*&#8226;\s*<\/span>\s*<span class="blog-listing__timestamp"\s*>(?:[^<]+)<\/span\s*>\s*<\/div>\s*<div class="blog-listing__comment-count">\s*<svg class="[^"]+">\s*<use\s*xlink:href="[^"]+"\s*><\/use>\s*<\/svg>\s*<span>\d+<\/span>\s*<\/div>\s*<\/div>\s*<h2 class="blog-listing__title">\s*<a\s*href="(?:[^"]+)"\s*>(?:[^<]+)<\/a\s*>\s*<\/h2>\s*<div class="blog-listing__summary">\s*(?:(?:(?:<p>(?:.(?!\/p>))+<\/p>\s*)|(?:<ul>\s*(?:<li>(?:.(?!\/li>))+<\/li>\s*)+<\/ul>))+)/is,

  regInfos: /<div class="blog-listing__post">\s*<div class="blog-listing__post-details">\s*<div>\s*<a\s*class="blog-listing__user-avatar"\s*href="\/fr\/wiki\/Utilisateur:[^"]+"\s*>\s*<img\s*class="blog-listing__user-avatar__image"\s*src="([^"]+)"\s*alt="[^"]+"\s*\/>\s*<\/a>\s*<a\s*href="[^"]+"\s*class="blog-listing__user-name"\s*>([^<]+)<\/a\s*>\s*<span class="blog-listing__bullet">\s*&#8226;\s*<\/span>\s*<span class="blog-listing__timestamp"\s*>([^<]+)<\/span\s*>\s*<\/div>\s*<div class="blog-listing__comment-count">\s*<svg class="[^"]+">\s*<use\s*xlink:href="[^"]+"\s*><\/use>\s*<\/svg>\s*<span>\d+<\/span>\s*<\/div>\s*<\/div>\s*<h2 class="blog-listing__title">\s*<a\s*href="([^"]+)"\s*>([^<]+)<\/a\s*>\s*<\/h2>\s*<div class="blog-listing__summary">\s*((?:(?:<p>(?:.(?!\/p>))+<\/p>\s*)|(?:<ul>\s*(?:<li>(?:.(?!\/li>))+<\/li>\s*)+<\/ul>))+)/is,
  regres: /<li\s*class="[^"]+">\s*<article>\s*<h1>\s*<a\s*href="[^"]+"\s*class="[^"]+"\s*data-wiki-id="\d+"\s*data-page-id="\d+"\s*data-title="[^"]+"\s*data-thumbnail="[^"]+"\s*data-position="\d+">[^<]+<\/a>\s*<\/h1>\s*<div\s*class="[^"]+">\s*((?:<span\s*class="searchmatch">[^<]+<\/span>)?[^<]+)+<\/div>/g,
};
